### ISSUE TITLE
When testing in django receiving KeyError: 'HTTP_USER_AGENT'

### ISSUE THREAD

**Issue by talbenbasat** [anx-ckreuzberger/django-rest-passwordreset#39] opened 2019-04-06 16:55 UTC
Hi,

When testing and posting to the api without HTTP_USER_AGENT or REMOTE_ADDR, There's a server error and KeyError.

The problem lays here:
```
token = ResetPasswordToken.objects.create(
                        user=user,
                        user_agent=request.META['HTTP_USER_AGENT'],
                        ip_address=request.META['REMOTE_ADDR']
                    )
```

django_rest_passwordreset/views.py line 136

The fix is to use get with default.

p.s. 
Thanks for the library

**Comment by talbenbasat** [comment] 2019-04-06 17:22
related PR

https://github.com/anx-ckreuzberger/django-rest-passwordreset/pull/40

**Comment by anx-ckreuzberger** [comment] 2019-04-09 05:39
Thanks for the hint and the PR. I wonder which setup you are using? 

Not having a user agent and remote address sounds like that your setup is missing a key component (e.g., forwarding headers to Django).

**Comment by anx-ckreuzberger** [comment] 2019-05-10 06:33
Thanks for the PR. 

Closing this as duplicate of #34 and the PR #40 has been merged.

**Closed by anx-ckreuzberger** 2019-05-10 06:33 UTC
